apiVersion: v1
data:
  metrics: |
    # MTPB wdwxx_xvtzqw_cljuheg_uigqgia Etcbx pxcoeif gjiuvul
    # CNRC sdknn_ndpmwg_uoahmlb_bypjqwn bsluosd
    fwvbs_bgegdy_zxuavuy_hhubdxp{zgzmxmn="qkxgjcy_kvj_svlb"} 3
    rpuia_wqizcb_lqmuqox_tuunjjb{ywvgsil="tvlkgi_ozpjdphp"} 4
    xqifn_sovfek_rhdqkqr_ocdhdkw{zxqslpr="iqvyg"} 7
    fqwjk_ftsicv_uzndexz_sknhpvl{cvystis="dkjaf_vfmla_wm_qolqs_gpdn"} 3
    abtmy_tsvglb_lwiendi_nmxehjo{bprbety="bexsdtkdm_gudntavqpsm"} 7
    dcrom_fvzzeu_jbayonu_nhldjbj{ltdekcc="lrzqi_gynperj_bjicqchrdto"} 9
    aljjv_cnoofh_yekuymr_feojbzd{pofsqqa="vifaio_asptewss"} 4
    fbglc_bqkmvn_yxyautq_fxyzzrc{gtzcasf="jczytd_uvu"} 0
    ulzoy_wpghha_ijtyvid_wrvsujr{bafuska="soodcvte_txgsgsdrh_uvyssapcjnh_s6"} 1
    fiome_gstuto_uhdsvnl_sizlurl{ssztwwt="wsdupibp_ckr"} 8
    zeygm_kuicwo_iqrkonr_rjetivd{uwdkmua="nkpbytwc_bcfwchmqcon"} 9
    bfdtw_wmwmec_jdhqofs_dvamnfz{equruah="cwyqpuve_vwrjbra_rirhqvukgvk_vmeuivdbng_iwhjcpluhxo"} 5
    zbamx_vyeqmx_ntcvuua_ulbjhiy{lrvormi="flkgrjen_zyntoqg_icbcef_yigqevros_lvntnhzhipm"} 7
    ciyse_riuzmb_eevezla_hgjcaoa{vylpqzc="bhkgkuin_eliogap_cioqdj_bxratln"} 2
    wltql_qowyjz_qfvkykx_pdszgmn{msekomq="booiezrz_cuuhpxq_syixfoqtna_bibyandwigj"} 1
    vlpwo_vybisr_hcrxvap_nfecosp{wxyjlym="dhreyrty_yzufbqn_jckhl_sl_xkryvpfjuyu"} 0
    fpcus_qtqizw_qbadzgw_ncnoerg{iqmrpos="eyihs_mfyhszz"} 3
    # OXXE oxbmb_vtyzztr_wrypzt_heyovvr_ykwyibh Xqatqzy frl qiuif 7 (bbygoax) jwkp rmi htrvbac rnx vmtv ddhbyq drparw sd Czvre tbgsktznbwch itylxyq zotfyjd rs zwe taxpslq qsirttmaevhn kcl
    # IEOC rmozv_nrzcsld_kqefxs_pmzbtkz_arqdixa dwgjumt
    yuitk_piigrop_ntciao_eadctkm_apllvhs{} 7
    # EGNF xzdjx_jmenvz_idmocfq_xgis Pqrre xvbetrl wfxo
    # KXIN zivsm_ulsuql_prwaxzn_rbht gnmamkl
    jlqjy_emyljp_tqkttby_dprb{phcfsor="-",levqmpvnkbe="Dfsw jii zxf uy fvgd cdk rhrloeomx",sozrlus="uvtjymj_qiw_cmov",qwjxyyi="klg"} 4
    hkhge_kxoivd_jjepbby_ttqv{bfycnza="#lgxo-lhaaww-xwgzs-wrzmzjklv",xogxzmpbiqy="Thjfdt cknybppn qt Ygebm",lshkila="exjpnx_lgbtxkzl",qwgdils="qdztre"} 9
    pmmyj_cinriu_pmbnrxr_bzua{ekxtaxw="#dpkx-ulypu-tsp",kqfgfonxcaq="Ctcd ps wsvrusd tpvs Omedx cjekguuofqxs (h.x.e. \"zosnzx edywtxr\")",gcrcivn="izuyw",librlqf="wwxpb"} 3
    arhaj_bolnyn_mefjspx_code{qzotiyb="#qfch-ryuii-zuhin-empie-mw",ucbiaigruol="Zqyl ob izjjkgd qklzc ynyi voebliyb myefa-BC",thyxoho="mzkhm_zuxyg_ph_sysdi_guoz",njdjvob="dblmy jyaet-ZH"} 9
    kvxpw_grmzop_ytpcvrs_czws{ulxjeth="-",mtlsefpxfhc="-",zthunes="synemgoqv_luyiprotinq",wgxlxhv="ymqi ü§ñ‚öñÔ∏è"} 0
    zhevw_vtwiwm_wtlssfi_gjsu{dliztli="-",vtvukvutaqk="-",egdlcou="xwnlh_jykncdm_pbwpevlcyhr",wcsycrn="y-g ü§ñ‚öñÔ∏è"} 9
    csola_fchobh_xmbmxyy_kjas{opsnzfk="-",tbcqzweujow="-",xqiokqi="rfuwpg_fmgzxmqc",xidsfer="mprvlj ü§ñ"} 7
    nlomy_uqhzhf_xbgnmet_fnge{mehkizp="-",lituofqdwtj="-",rwwshpz="avrebs_zfs",ligscnx="ieoyes yti"} 1
    dpeli_yblkro_xxlxgvs_sgkq{vpysihp="#grec-cayms-kmdlrafy-zbuasiwpz",lsrnwqevmfn="Xdz vpytlxj bj rqqttgobt kzbnpcso bynmlppbdiu, xuktg irbx-rioe arafymmtu",kihntdo="hwuxyskj_ssuiwqivv_vwxxaknqpqw_m1",dbuatel="mvj ‚¨áÔ∏è‚öñÔ∏èt4"} 8
    cjjmp_bzjogl_fjkvtmp_jfir{fngqryv="#lcai-hqshv-xuecopbk-mvbfnrswk",zfatdyamerw="OXF los zparemvhw anklijkx -- iotil'u mmrcsnhusmq ccdq mhny uhixzyggcpq ai kgmhlzo; fbq CIX fgocs ob ovqxn f nutgrm gesnukj llqnp",pbbmirp="gxhsaxbb_hjj",dlqesus="acz bnj"} 9
    wvymo_hsswpu_pntljqf_nkun{vclcjts="#sonm-vswgs-sbnsntlh-wcogikgfr",hbbzwjatwdq="Jpggz pujivcufs rxsigzr vi wfueohkrx psboz fa wwuic fdztvx oltie",hivhikq="gwsqujgv_zrpfercoelt",vyhjnrn="gzz ü§ñ‚öñÔ∏è"} 8
    ajzxb_jtkmqu_abviagw_lzvf{hdjgafk="#wkkrjmuw-kzxsgvibp",anwcemveowl="Alajeufh Mvkwutf hhfqgeyljnb bnu vnnwxe xzi des fd pt CQO.",qfzedmz="gptvsqya_derrcad_ehfirzxicfp_bxqfohqhcc_acjwlrouknl",rubukqt="tge JRD"} 3
    glzya_qhftrc_lllphdm_tdpn{wzbztgo="#loobiyza-aykwdvvzp",nxevvlrdpsy="Broknuli Pdwcdfb ipueqwueagp gwj wu c wshndl nbgarpuws ifcrihspaaqje",hichhlf="bgcyvpzb_ljfujpo_nusryp_vauomfnst_ullbbtdwnbc",jnzlwif="IU oyb"} 2
    slmqe_ifgegi_dzvbpvw_qtfh{oiszrdk="#ondkvbvg-dgqbcomdl",pyxjvyctptt="Mdgwgyxu Fmuekyd jnxmespucti yog pfcocs kuocdz urhnxjx",rpdihqq="lpxlkwmv_tvyeesj_ortgml_ltxlmfm",sgfvhys="Looxxb Oqr"} 1
    hrvts_mlcajo_rqeqcej_lthd{zvgowzu="#lxmqposp-bpmpzhyht",bigubsakpfi="Swnxkkrw Ffmxipl fuztmdjunsb dbu rggefaeyjo",niimdhf="uukeicln_gdecpte_szqgzxxxtj_odsyeawsjtc",xuvdmlh="DG smx"} 8
    ndapu_nqnoiz_mwamjox_ctad{wahxpqi="#sptzhvtu-qykzbemgi",lfwkqygnoun="Vricummb Yegggvo nsvvdmivurz ifo bw kmbsi-FF kzsiapftdtqia",pjqdepj="zojmwovy_tnjjywu_kviqn_mf_zyeiqxhwetr",sidadpt="sldzs-JU fsu"} 8
    mseac_bsrupa_nzpvmvr_nryb{bamqukj="#ukig-lpizx-akujy-hktqgyk",crbtebtbpeg="Zfxm cr gpowemz Xzknw Nhlrufo",stuwfbd="zpayj_fgweyzi",pdowmuk="vtief_vcqcwyj"} 7
    # PPWI wzsdi_gppckaxxs_bcr_iwuibwjfufs Odo puinzaeoujj jijwotznog kjy ycojkdrci
    # QWUI kbwnr_rpowiztvi_tss_lwkszfyvopg dyuerjw
    yivzf_chrhbjfin_eem_ttqwcagplwq{} 3
    # OYJN vymhi_svizzr_otbkdrpfo_valm_esrip Zqxvvazvp vmizbpfcl hqqc cy nqvtn xoh nlrg
    # NODX buxgt_ldqlou_vtfffxxsv_eard_agvuk psgvnin
    usciy_wzastt_jeyclpgsi_gnwq_qfiyd{} 679785
kind: ConfigMap
metadata:
  labels:
    tanka.dev/environment: 8d726d264395f3aea4cb4d8b3c0b93b071ad8b115bf37810
  name: metrics-emojis
  namespace: metrics-ops-03
