[package]
name = "jrsonnet-parser"
description = "jsonnet language parser and AST"
version = "0.4.2"
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
license = "MIT"
edition = "2021"

[features]
exp-destruct = []

[dependencies]
jrsonnet-interner = { path = "../jrsonnet-interner", version = "0.4.2" }
jrsonnet-gcmodule = { version = "0.3.4" }

static_assertions = "1.1.0"

peg = "0.8.0"

serde = { version = "1.0", features = ["derive", "rc"], optional = true }

[dev-dependencies]
jrsonnet-stdlib = { path = "../jrsonnet-stdlib", version = "0.4.2" }
