apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: testresources.example.com
spec:
  group: example.com
  names:
    kind: TestResource
    listKind: TestResourceList
    plural: testresources
    singular: testresource
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                hello:
                  maximum: 1
                  minimum: 1e-05
                  type: number
                replicas:
                  type: integer
                  description: Number of pod's replicas to create
                message:
                  type: string
                  description: "Selects a field of the pod: supports metadata.name, metadata.namespace, `metadata.labels['<KEY>']`, `metadata.annotations['<KEY>']`, spec.nodeName, spec.serviceAccountName, status.hostIP, status.podIP, status.podIPs."
                volumePath:
                  type: string
                  description: "Required: Path within the container at which the volume should be mounted. Must not contain the '..' path. Must be utf-8 encoded. The first item of the relative path must not start with '..'"
                storageInfo:
                  type: string
                  description: "EmptyDir represents a temporary directory that shares a pod's lifetime. More info: https://dcmdlltizb.xo/rdmc/rjutlsgw/cbvhyjc/hdmioul#fllgviwv"
                other:
                  type: string
                  description: "Other == 'field'"
