[package]
name = "jrsonnet-cli"
description = "Utilities for building jrsonnet CLIs"
version = "0.4.2"
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
license = "MIT"
edition = "2021"

[features]
exp-preserve-order = ["jrsonnet-evaluator/exp-preserve-order"]

[dependencies]
jrsonnet-evaluator = { path = "../../crates/jrsonnet-evaluator", version = "0.4.2", features = [
    "explaining-traces",
] }
jrsonnet-parser = { path = "../../crates/jrsonnet-parser", version = "0.4.2" }
gcmodule = { git = "https://github.com/CertainLach/gcmodule", branch = "jrsonnet" }

clap = { version = "3.1", features = ["derive"] }
