[package]
name = "jrsonnet-cli"
description = "Utilities for building jrsonnet CLIs"
version = "0.4.2"
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
license = "MIT"
edition = "2021"

[features]
exp-preserve-order = [
    "jrsonnet-evaluator/exp-preserve-order",
    "jrsonnet-stdlib/exp-preserve-order",
]
legacy-this-file = ["jrsonnet-stdlib/legacy-this-file"]

[dependencies]
jrsonnet-evaluator = { path = "../../crates/jrsonnet-evaluator", version = "0.4.2", features = [
    "explaining-traces",
] }
jrsonnet-parser = { path = "../../crates/jrsonnet-parser", version = "0.4.2" }
jrsonnet-gcmodule = { version = "0.3.4" }
jrsonnet-stdlib = { path = "../../crates/jrsonnet-stdlib", version = "0.4.2" }

clap = { version = "4.0", features = ["derive"] }
