apiVersion: apps/v1
kind: Deployment
metadata:
  name: flagger-{{ .Values.clusterName }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flagger
  template:
    metadata:
      labels:
        app: flagger
    spec:
      containers:
        - name: flagger
          image: flagger:latest
