apiVersion: v1
data:
  envoy.yaml: |
    static_resources:
        listeners:
            - filter_chains:
                - filters:
                    - typed_config:
                        '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                        http_filters:
                            - typed_config:
                                '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
kind: ConfigMap
metadata:
  name: envoy-config
  namespace: default
